"""Add organization and user_organization models

Revision ID: 763a380ce05d
Revises: da04558eb951
Create Date: 2025-09-23 06:03:52.191071+00:00

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '763a380ce05d'
down_revision: Union[str, None] = 'da04558eb951'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('organizations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('slug', sa.String(length=100), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('website', sa.String(length=255), nullable=True),
    sa.Column('logo_url', sa.String(length=500), nullable=True),
    sa.Column('plan', sa.String(length=50), nullable=False),
    sa.Column('billing_email', sa.String(length=255), nullable=True),
    sa.Column('stripe_customer_id', sa.String(length=255), nullable=True),
    sa.Column('subscription_status', sa.String(length=50), nullable=False),
    sa.Column('settings', sa.JSON(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('max_agents', sa.Integer(), nullable=True),
    sa.Column('max_users', sa.Integer(), nullable=True),
    sa.Column('max_documents_per_agent', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_organizations_id'), 'organizations', ['id'], unique=False)
    op.create_index(op.f('ix_organizations_name'), 'organizations', ['name'], unique=False)
    op.create_index(op.f('ix_organizations_slug'), 'organizations', ['slug'], unique=True)
    op.create_table('user_organizations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('organization_id', sa.Integer(), nullable=False),
    sa.Column('role', sa.String(length=20), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('invited_by_user_id', sa.Integer(), nullable=True),
    sa.Column('invitation_token', sa.String(length=255), nullable=True),
    sa.Column('invitation_expires_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('invitation_accepted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['invited_by_user_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('invitation_token'),
    sa.UniqueConstraint('user_id', 'organization_id', name='unique_user_organization')
    )
    op.create_index(op.f('ix_user_organizations_id'), 'user_organizations', ['id'], unique=False)
    # Create a default organization first
    organizations_table = sa.table('organizations',
        sa.column('id', sa.Integer),
        sa.column('name', sa.String),
        sa.column('slug', sa.String),
        sa.column('plan', sa.String),
        sa.column('subscription_status', sa.String),
        sa.column('is_active', sa.Boolean),
        sa.column('max_agents', sa.Integer),
        sa.column('max_users', sa.Integer),
        sa.column('max_documents_per_agent', sa.Integer)
    )

    # Insert default organization
    op.execute(
        organizations_table.insert().values(
            id=1,
            name='Default Organization',
            slug='default-org',
            plan='free',
            subscription_status='active',
            is_active=True,
            max_agents=3,
            max_users=1,
            max_documents_per_agent=10
        )
    )

    # Add columns as nullable first
    op.add_column('agents', sa.Column('organization_id', sa.Integer(), nullable=True))
    op.add_column('agents', sa.Column('total_conversations', sa.Integer(), nullable=True, server_default='0'))
    op.add_column('agents', sa.Column('total_messages', sa.Integer(), nullable=True, server_default='0'))
    op.add_column('agents', sa.Column('last_used_at', sa.DateTime(timezone=True), nullable=True))

    # Update existing agents to belong to default organization
    op.execute("UPDATE agents SET organization_id = 1 WHERE organization_id IS NULL")

    # Make organization_id non-nullable
    op.alter_column('agents', 'organization_id', nullable=False)

    # Create foreign key
    op.create_foreign_key(None, 'agents', 'organizations', ['organization_id'], ['id'])

    # Create default user organization relationships for existing users
    user_orgs_table = sa.table('user_organizations',
        sa.column('user_id', sa.Integer),
        sa.column('organization_id', sa.Integer),
        sa.column('role', sa.String),
        sa.column('is_active', sa.Boolean)
    )

    # Add all existing users to the default organization as owners
    op.execute("""
        INSERT INTO user_organizations (user_id, organization_id, role, is_active)
        SELECT id, 1, 'owner', true FROM users
        WHERE NOT EXISTS (
            SELECT 1 FROM user_organizations
            WHERE user_id = users.id AND organization_id = 1
        )
    """)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'agents', type_='foreignkey')
    op.drop_column('agents', 'last_used_at')
    op.drop_column('agents', 'total_messages')
    op.drop_column('agents', 'total_conversations')
    op.drop_column('agents', 'organization_id')
    op.drop_index(op.f('ix_user_organizations_id'), table_name='user_organizations')
    op.drop_table('user_organizations')
    op.drop_index(op.f('ix_organizations_slug'), table_name='organizations')
    op.drop_index(op.f('ix_organizations_name'), table_name='organizations')
    op.drop_index(op.f('ix_organizations_id'), table_name='organizations')
    op.drop_table('organizations')
    # ### end Alembic commands ###