"""Update schema with proper field names

Revision ID: da04558eb951
Revises: d8673cc3f93b
Create Date: 2025-09-23 00:12:29.599571+00:00

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'da04558eb951'
down_revision: Union[str, None] = 'd8673cc3f93b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('agents', sa.Column('user_id', sa.Integer(), nullable=False))
    op.drop_constraint('agents_owner_id_fkey', 'agents', type_='foreignkey')
    op.create_foreign_key(None, 'agents', 'users', ['user_id'], ['id'])
    op.drop_column('agents', 'owner_id')
    op.add_column('conversations', sa.Column('conv_metadata', sa.JSON(), nullable=True))
    op.add_column('conversations', sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True))
    op.add_column('conversations', sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True))
    op.drop_column('conversations', 'last_message_at')
    op.drop_column('conversations', 'started_at')
    op.add_column('documents', sa.Column('content_type', sa.String(), nullable=False))
    op.add_column('documents', sa.Column('size', sa.Integer(), nullable=False))
    op.add_column('documents', sa.Column('content_hash', sa.String(), nullable=True))
    op.add_column('documents', sa.Column('doc_metadata', sa.JSON(), nullable=True))
    op.drop_column('documents', 'file_size')
    op.drop_column('documents', 'file_type')
    op.add_column('messages', sa.Column('msg_metadata', sa.JSON(), nullable=True))
    op.add_column('users', sa.Column('password_hash', sa.String(), nullable=False))
    op.add_column('users', sa.Column('name', sa.String(), nullable=True))
    op.add_column('users', sa.Column('plan', sa.String(), nullable=True))
    op.drop_column('users', 'hashed_password')
    op.drop_column('users', 'full_name')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('full_name', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('users', sa.Column('hashed_password', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.drop_column('users', 'plan')
    op.drop_column('users', 'name')
    op.drop_column('users', 'password_hash')
    op.drop_column('messages', 'msg_metadata')
    op.add_column('documents', sa.Column('file_type', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.add_column('documents', sa.Column('file_size', sa.INTEGER(), autoincrement=False, nullable=False))
    op.drop_column('documents', 'doc_metadata')
    op.drop_column('documents', 'content_hash')
    op.drop_column('documents', 'size')
    op.drop_column('documents', 'content_type')
    op.add_column('conversations', sa.Column('started_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=True))
    op.add_column('conversations', sa.Column('last_message_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True))
    op.drop_column('conversations', 'updated_at')
    op.drop_column('conversations', 'created_at')
    op.drop_column('conversations', 'conv_metadata')
    op.add_column('agents', sa.Column('owner_id', sa.INTEGER(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'agents', type_='foreignkey')
    op.create_foreign_key('agents_owner_id_fkey', 'agents', 'users', ['owner_id'], ['id'])
    op.drop_column('agents', 'user_id')
    # ### end Alembic commands ###